### ISSUE TITLE
Escrow to JAMF is not working

### ISSUE THREAD

**Issue by mvught** [robjschroeder/FileVault-Personal-Recovery-Key-Reissue#2]
He Rob,

The Escrow to JAMF is not working. Pleas check: https://raw.githubusercontent.com/thom-bartlett/jss-filevault-reissue/main/reissue_filevault_recovery_key.sh
I have merged thing together and now its working. Some small changes.

**Comment by robjschroeder** [comment]
Thank you for the insight @mvught, I have taken these suggestions and re-vamped the script. Can you please test out version 1.3.0 and let me know what you get?

**Comment by robjschroeder** [comment]
I have verified on my end that keys are getting escrowed into Jamf.

**Comment by broojamfburd** [comment]
Good afternoon Rob, 
I am also experiencing the same issue on some of my newer Jamf servers (I work at a MSP). Same exact script, but it works for some servers and not others. I am trying to figure out why it's not working. It prompts for the password, runs the script, and then the key never shows up in Jamf. The policy logs show no errors (see screenshot). This is happening on different Macs and OSs. The only consistent thing is all the servers are now (created in the past month). 

![Screenshot 2024-01-17 at 3 03 07 PM](https://github.com/robjschroeder/FileVault-Personal-Recovery-Key-Reissue/assets/36173452/d9137791-8a24-4bae-b8eb-ef0f26856209)

Thank you for any assistance, I will keep poking around!
