### ISSUE TITLE
URL for Swift Download Changed.

### ISSUE THREAD

**Issue by brookeburdick** [robjschroeder/FileVault-Personal-Recovery-Key-Reissue#3]
I am not sure how recent this is, but I was getting "Team ID verification failed, could not continue..." I decided to run the Curl command in Terminal, and it came back with a message 
"message": "Moved Permanently",
  "url": "https://api.github.com/repositories/346831918/releases/latest",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"

I replaced the URL in the script with that new one, and it worked again. Not sure why, I am on Sonoma though.

**Comment by brookeburdick** [comment]
Looking at my logs, it looks like the error started around August 23, 2023.

**Comment by robjschroeder** [comment]
Hey @broojamfburd I did update about a month ago, have you tried `version 1.4.0` ?
